name: deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v3
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.12
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
